#!/bin/bash
# This file is from https://github.com/Albert-S-Briscoe/projectsandcastlefix

DISK=0
DISKS=`ls -1 /dev/disk0s1s* | sort -V`

if [[ -z $DISKS ]]; then
	# I can't find any way to delete accidentally created apfs volumes. This should help prevent making them in the first place.
	echo "Can't find any apfs volumes. Something is very wrong."
	exit 1
fi

# search for 
for i in ${DISKS}
do
	LABEL=`/System/Library/Filesystems/apfs.fs/apfs.util -p $i`
	if [ "${LABEL}" == "Android" ]; then
		DISK=$i
		break;
	fi
done
if [ ! -b ${DISK} ]; then
	echo "Creating new Android volume"
	newfs_apfs -A -v Android -e /dev/disk0s1
fi

DISK=
DISKS=`ls /dev/disk0s1s* | sort -V`

for i in ${DISKS}
do
	LABEL=`/System/Library/Filesystems/apfs.fs/apfs.util -p $i`
	if [ "${LABEL}" == "Android" ]; then
		DISK=$i
		break;
	fi
done

if [ ! -b ${DISK} ]; then 
	echo "Android volume not found. This should have been caught earlier"
	exit 1
fi

echo "Mounting ${DISK}"
mkdir -p /tmp/mnt
mount -t apfs ${DISK} /tmp/mnt 
if [ $? -ne 0 ]; then
	echo "failed to mount volume. Are you running as root?";
	exit 1
fi

if [ -e /tmp/mnt/nand ]; then
	echo "Nand image already downloaded."
else
	rm -rf /tmp/mnt/nand
	echo "Starting to download nand. This will take a few minutes"
	wget http://assets.checkra.in/downloads/sandcastle/88b1089d97fe72ab77af8253ab7c312f8e789d49209234239be2408c3ad89a34/nand.gz -O /tmp/mnt/nand.gz
	if [ $? -ne 0 ]; then
		echo "Failed to download nand. Are you connected to wifi?"
		umount /tmp/mnt
		echo "unmounted /tmp/mnt"
		exit 1
	fi
	echo "Decompressing nand image"
	gunzip -d /tmp/mnt/nand.gz
	if [ $? -ne 0 ]; then
		echo "Failed to decompress nand. Network interrupted? gzip not installed?"
		umount /tmp/mnt
		echo "unmounted /tmp/mnt"
		exit 1
	fi
	sync
fi

echo "Applying touchscreen/WiFi patch and copying driver files."

# The Hack.
echo -n "  " | dd bs=1 seek=1145078249 count=2 status=none conv=notrunc of=/tmp/mnt/nand

# The Fix.
mkdir -p /tmp/mnt/usr/share/firmware/
cp -rn /usr/share/firmware/* /tmp/mnt/usr/share/firmware/

umount /tmp/mnt
echo "unmounted /tmp/mnt"
