#!/bin/sh

DISK=0
DISKS=`ls /dev/disk0s1s*`
DISKS=`ls /dev/disk0s1s*`

for i in ${DISKS}
do
	LABEL=`/System/Library/Filesystems/apfs.fs/apfs.util -p $i`
	if [ "${LABEL}" == "Android" ]; then
	    DISK=$i
	    break;
        fi
done
if [ ! -b ${DISK} ]; then
	newfs_apfs -A -v Android -e /dev/disk0s1
fi

DISK=
DISKS=`ls /dev/disk0s1s*`

for i in ${DISKS}
do
	LABEL=`/System/Library/Filesystems/apfs.fs/apfs.util -p $i`
	if [ "${LABEL}" == "Android" ]; then
	    DISK=$i
	    break;
        fi
done
if [ -b ${DISK} ]; then 
	mkdir -p /tmp/mnt
	echo "Mounting ${DISK}"
	mount -t apfs ${DISK} /tmp/mnt 
	if [ $? -ne 0 ]; then
            echo "failed to mount disk";
  	    exit 1
        fi
	rm -rf /tmp/mnt/nand*
	echo "Starting to download nand. This will take a few minutes"
	wget http://assets.checkra.in/downloads/sandcastle/88b1089d97fe72ab77af8253ab7c312f8e789d49209234239be2408c3ad89a34/nand.gz        
	if [ $? -ne 0 ]; then
		echo "Failed to download nand. Are you connected to wifi?"
	        umount /tmp/mnt
		exit 1;
	fi
	echo "Decompressing nand image"
	mv /var/root/nand.gz /tmp/mnt
	gunzip -d /tmp/mnt/nand.gz
        if [ $? -ne 0 ]; then
                echo "Failed to decompress nand. Wifi disconnected?"
                umount /tmp/mnt
                exit 1;
        fi
	sync
	umount /tmp/mnt
else
	echo "There was an error"
	exit 1
fi